function mantle(){var Q='',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',jb='"><\/script>',$='#',Gb='&',Fc='.cache.html',ab='/',mb='//',Zb='05ED4479C0E4CD57F0E66510040312BD',$b='0DA750BB9BB33042AEF7D1F2C3A5C42E',ac='13854B80518720DA5625F04900E386DC',bc='2B8CA72A9ABE1765423A50CE0215A356',dc='2DAF05616E36E71DA14D9DD173CE198B',ec='4364F7F133E7F7262E9B4799A68D1E4C',gc='46A5B049716D6036AE0513C402E673AA',hc='4CB0FB11052F668284C52EFB87550FE8',ic='5237A3246F854804B19686EFB314F0B6',jc='5A939DDB6C5D67EC97C0B37C43B3ED8E',kc='7126B495AA6B546B6FEE5B0D4B5A4F64',lc='7BD23302068F4072E6235DA67C62B7BD',mc='7DF64431498D17F5245B4F201F05D08B',nc='860CDD716C490F25D5BAD453A1D8974D',oc='861710D1B5E2190E547C5F57DCF3736D',pc='9B763854FE7AC96E6A1AC115D7C5D604',qc='9C8E7D73263EA2221D0E93A31AAC5360',Ec=':',qb='::',Nc='<script defer="defer">mantle.onInjectionDone(\'mantle\')<\/script>',ib='<script id="',tb='=',_='?',rc='B6822957D28CB7F592E156A06C372CFE',sc='B78F502DA73E57C4BC647D2F7391F0DA',tc='B8B3637DB173813E3ACD48E87BD2EA0D',uc='BF3B35E97F1CE1F87BE30C7D21D90921',vb='Bad handler "',vc='CDB5939BDDCBD363C2C322F5871E9497',wc='D51DAF6C801AE2F2191CCD3809BAEADC',Mc='DOMContentLoaded',xc='E6E86950601719B713D7A0BAC35D9AE4',yc='E6FD726A6B19098E13BE1AE35F63FA64',zc='E78678DBE7F8DD081CE9393669F8E53B',Ac='E8FD92B9013728E22418B0971DCC9E31',Bc='EA84E020983452B7357E3B5EADB55E9B',Cc='F30194F0811193830C7DA70732B6C048',Dc='F36384B5823F56E479578DDBEB7D7967',kb='SCRIPT',Jb='Unexpected exception in locale detection, using default: ',Ib='_',Hb='__gwt_Locale',hb='__gwt_marker_mantle',lb='base',db='baseUrl',U='begin',T='bootstrap',cb='clear.cache.gif',sb='content',_b='de',Yb='default',Eb='en',Z='end',cc='fr',Sb='gecko',Tb='gecko1_8',V='gwt.codesvr=',W='gwt.hosted=',X='gwt.hybrid',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',Lc='head',Wb='hosted.html?mantle',Kc='href',Rb='ie6',Qb='ie8',Pb='ie9',zb='iframe',bb='img',fc='ja',Ab="javascript:''",Hc='link',Vb='loadExternalRefs',Db='locale',Fb='locale=',R='mantle',fb='mantle.nocache.js',pb='mantle::',nb='meta',Cb='moduleRequested',Y='moduleStartup',Ob='msie',ob='name',Lb='opera',Bb='position:absolute;width:0;height:0;border:none',Ic='rel',Nb='safari',eb='script',Xb='selectingPermutation',S='startup',Jc='stylesheet',gb='undefined',Ub='unknown',Kb='user.agent',Mb='webkit',Gc='xul.css';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=Q,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:U});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(V)!=-1||(c.indexOf(W)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(X)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(R);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return I(a)}}mantle=null;c.gwtOnLoad(z,R,t,y);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Z})}}
function D(){function e(a){var b=a.lastIndexOf($);if(b==-1){b=a.length}var c=a.indexOf(_);if(c==-1){c=a.length}var d=a.lastIndexOf(ab,Math.min(c,b));return d>=0?a.substring(0,d+1):Q}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(bb);b.src=a+cb;a=e(b.src)}return a}
function g(){var a=G(db);if(a!=null){return a}return Q}
function h(){var a=n.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(fb)!=-1){return e(a[b].src)}}return Q}
function i(){var a;if(typeof isBodyLoaded==gb||!isBodyLoaded()){var b=hb;var c;n.write(ib+b+jb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=kb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return Q}
function j(){var a=n.getElementsByTagName(lb);if(a.length>0){return a[a.length-1].href}return Q}
function k(){var a=n.location;return a.href==a.protocol+mb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==Q){l=h()}if(l==Q){l=i()}if(l==Q){l=j()}if(l==Q&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(nb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(ob),g;if(f){f=f.replace(pb,Q);if(f.indexOf(qb)>=0){continue}if(f==rb){g=e.getAttribute(sb);if(g){var h,i=g.indexOf(tb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=Q}u[f]=h}}else if(f==ub){g=e.getAttribute(sb);if(g){try{A=eval(g)}catch(a){alert(vb+g+wb)}}}else if(f==xb){g=e.getAttribute(sb);if(g){try{z=eval(g)}catch(a){alert(vb+g+yb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function I(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var J;function K(){if(!J){J=true;var a=n.createElement(zb);a.src=Ab;a.id=R;a.style.cssText=Bb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Cb});a.contentWindow.location.replace(t+M)}}
w[Db]=function(){var b=null;var c=Eb;try{if(!b){var d=location.search;var e=d.indexOf(Fb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Gb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=G(Db)}if(!b){b=m[Hb]}if(b){c=b}while(b&&!F(Db,b)){var h=b.lastIndexOf(Ib);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Jb+a)}m[Hb]=c;return b||Eb};v[Db]={de:0,'default':1,en:2,fr:3,ja:4};w[Kb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Lb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=9}())return Pb;if(function(){return b.indexOf(Ob)!=-1&&n.documentMode>=8}())return Qb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;return Ub};v[Kb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};mantle.onScriptLoad=function(){if(J){r=true;C()}};mantle.onInjectionDone=function(){q=true;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:Z});C()};E();D();var L;var M;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(R))){m.location.reload();return}M=Wb;L=Q}o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Xb});if(!B()){try{H([Yb,Rb],Zb);H([Yb,Lb],$b);H([_b,Lb],ac);H([Yb,Nb],bc);H([cc,Tb],dc);H([_b,Nb],ec);H([fc,Rb],gc);H([_b,Tb],hc);H([fc,Pb],ic);H([cc,Rb],jc);H([fc,Qb],kc);H([fc,Nb],lc);H([fc,Lb],mc);H([cc,Pb],nc);H([Eb,Rb],oc);H([Eb,Tb],pc);H([Eb,Qb],qc);H([_b,Qb],rc);H([_b,Rb],sc);H([Yb,Tb],tc);H([Eb,Nb],uc);H([Yb,Pb],vc);H([Yb,Qb],wc);H([cc,Qb],xc);H([fc,Tb],yc);H([Eb,Lb],zc);H([cc,Lb],Ac);H([cc,Nb],Bc);H([_b,Pb],Cc);H([Eb,Pb],Dc);L=x[I(Db)][I(Kb)];var N=L.indexOf(Ec);if(N!=-1){y=Number(L.substring(N+1));L=L.substring(0,N)}M=L+Fc}catch(a){return}}var O;function P(){if(!s){s=true;if(!__gwt_stylesLoaded[Gc]){var a=n.createElement(Hc);__gwt_stylesLoaded[Gc]=a;a.setAttribute(Ic,Jc);a.setAttribute(Kc,t+Gc);n.getElementsByTagName(Lc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Mc,P,false)}if(O){clearInterval(O)}}}
if(n.addEventListener){n.addEventListener(Mc,function(){K();P()},false)}var O=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K();P()}},50);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Z});o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Vb,millis:(new Date).getTime(),type:U});n.write(Nc)}
mantle();